name: Auto Crate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */7 * * *'

jobs:
  claim-crate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Run Crate Claimer Script
        env:
          FENTRY_SESSION_COOKIE: ${{ secrets.FENTRY_SESSION_COOKIE }}
        run: python main.py
