# .github/workflows/claim.yml

name: Fentry Crate Claimer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  claim-crate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- NEW: Cache pip dependencies ---
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip # The directory where pip stores its cache
          # The key identifies the cache. It includes the OS and a hash of the requirements file.
          # If requirements.txt changes, the key changes, and a new cache is created.
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # --- NEW: Cache Playwright browsers ---
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright # The directory where Playwright stores browser binaries
          # This key also depends on the requirements file, as a new Playwright version might need a new browser.
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # --- UPDATED: Install dependencies using requirements.txt ---
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Run Crate Claimer Script
        env:
          FENTRY_SESSION_COOKIE: ${{ secrets.FENTRY_SESSION_COOKIE }}
        run: python main.py